### ISSUE TITLE
Streaming of sensor output to another notebook script or a file

### ISSUE THREAD

**Issue by goatchurchprime** [adafruit/jupyter_micropython_kernel#9]
The Arduino/Processing combination provided the capability to print the readings of a sensor from a loop to the serial.out and direct it to a processing script that parsed the numbers and created a realtime graph.  
    https://itp.nyu.edu/physcomp/labs/labs-serial-communication/serial-output-from-an-arduino/

Note that in the implementation it takes two separate programs to make this happen.  

This could have been done using multiple kernels in the same notebook, but this kind of thing didn't work out so well in practice:  https://github.com/jupyterhub/jupyterhub/issues/202

You could still do this using a different notebook page that could either read from a file, serial socket or websocket that's being filled by a micropython script/cell contents from the first notebook page.  

(Graphing numbers that were printed to the serial buffer was seen as so fundamental it got put into the IDE   https://www.youtube.com/watch?v=Q7rJkEjdoYE )

The following workflow could then be supported:
   1) raw sensor data streamed to python in a notebook where it can be plotted using matplotlib and analysed using scipy 
   2) various ARIMA-type filters applied to the sensor data to identify the underlying levels of noise and necessary sample rates
   3) the filter with the best constants could be implemented in micropython and loaded into the board so we get clean properly understood sensor data
   4) quality and application of sensor data massively improves because we're no longer hacking filters into the sensors blindly

**Comment by goatchurchprime** [comment]
Would like to use %%capture but this won't work as saves into a variable rather than into a file

**Comment by ladyada** [comment]
@willingc heya carol, i think i understand what this is but do you know if its at all possible? you'd be running python both locally (numpy etc) and 'remotely' (on the micropy/circuitpy board) - i sorta think it isnt?
(if it is, we'd be happy to implement it! :)

**Comment by willingc** [comment]
@ladyada Possible (though I haven't tried streaming). Definitely can get data from a circuitpython board via the notebook (see https://github.com/willingc/circuitpython_kernel in the examples). The notebook is installed and run from your local computer. We could run numpy on the local system as well. Feel free to use any code from my repo if it helps though it's still pretty hacky/incomplete on how it gets the vid/pid for connection.

**Comment by goatchurchprime** [comment]
@ladyada  There's another implementation of this useful application: 
    https://github.com/goatchurchprime/jupyter_micropython_kernel/
If you took all its features I wouldn't need to maintain it.  (See the developer notebooks for some of them, including running the esptool directly to install micropython, file uploads, and it can work over webrepl.)

**Comment by tdicola** [comment]
Hrm so I don't think this is really feasible or the best place to put real-time graphing.  From what I've seen Jupyter notebooks aren't setup for real-time graphing, at least with matplotlib.  You can kind of hack it and make it work but matplotlib and friends are really just for static graph generation.  Really we'd want to investigate something like bokeh or other environments that are purpose built for realtime graphs.  I know there's some Jupyter and Bokeh integration but I'm not sure how far along it is yet: https://github.com/bokeh/bokeh-notebooks  There's actually nothing stopping someone from using bokeh right now to realtime graph data written to the serial port though, and that's definitely the right way to approach real-time graphs of sensor data vs. trying to create multiple Jupyter kernels and marshall communication between them (and then deal with how to get realtime graphs updating in a notebook.. another set of complex issues).  I'm going to close this with the pointer to use bokeh and its examples: https://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html#userguide-quickstart  Just read data using pyserial and send it to your bokeh graph to update.
